# Generated by Django 3.1.4 on 2020-12-31 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=250)),
                ('student_email', models.EmailField(max_length=250)),
                ('student_dob', models.DateField()),
            ],
            options={
                'ordering': ('student_id',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=250)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'ordering': ('department_name',),
            },
        ),
    ]
